// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xatzdkohsbuntmfgiehq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhdHpka29oc2J1bnRtZmdpZWhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NjQ1NTgsImV4cCI6MjA2ODM0MDU1OH0.CvyRe2NCx7eB9RgZucPN-M5s-bEBdTXLP9ZkfjnR77Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});